#!/usr/bin/env bash
# note requires pandoc and sed

function usage {
    cat <<EOF
usage: ./convert-handout file.md
EOF
}

function add-foldable-sections {
    # Input in html will be converted such that h1 elements
    # are buttons and content between them is wrapped in divs.
    # This aids in folding.
    local doc
    doc=$(sed -e 's/<h1>/<\/div>\n<button class="foldable">/g' \
	      -e 's/<\/h1>/<\/button>\n<div class="content">/g' $1)

    # Slice off the first </div> tag and add a </div> tag to the end
    echo -e "${doc:7}\n</div>"
}

# Check usage
if [[ ! -n "$1" ]]; then
    usage
    exit
fi

add-foldable-sections $1
